#ifndef VV_CONSTANTS
#define VV_CONSTANTS

#define MAX_CUBES 100000

#define SQUARES_PER_CUBE 6

#define VERTICES_PER_CUBE 24
#define VERTEX_INDICES_PER_CUBE 36

#define VERTICES_PER_SQUARE VERTICES_PER_CUBE*VERTICES_PER_CUBE

#define ONE_SECOND_IN_MS 1000


#endif
